### Create FriendRequest
POST  http://localhost:8080/api/friends/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkdWMiLCJpYXQiOjE1OTU4NjU1MjIsImV4cCI6MTU5NTk1MTkyMn0.BpIWH48u1XrkdCDmyMyby0H5QHWDSygV1snjNRgzJWPz5J936bSfcisMlHOYYXDyKNBq7o0qPd9UVQEl2vRZjA


### Confirm FriendRequest
PUT  http://localhost:8080/api/friends/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoaWV1IiwiaWF0IjoxNTk1OTE5OTA4LCJleHAiOjE1OTYwMDYzMDh9.a6tC4HZhyOclyqhoxdmdg9uM6vJxefpDOm09iJeUpxiaKYGUuRhuCDAKIFP68zEat9wkgXZn5MQcGLNSNt7hKQ


### Delete FriendRelationship or Delete Friend Request
DELETE http://localhost:8080/api/friends/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1ODYyNTg0LCJleHAiOjE1OTU5NDg5ODR9.MDs-XgduhDPFVz--aPO5o6PrNH7dvd2CguFRg8ohPkmCArxfbCGRoeiVeh3B7rGEqKxNv5RkNq5RZQ2aXyWg6w


### Get list Friend of user
GET http://localhost:8080/api/friends/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1OTE5OTYxLCJleHAiOjE1OTYwMDYzNjF9.tXmQUwVVvWjWX7FxAmpSfFyUfX2Xgs8GrwzjlRSJI3pLPx-w7f3_2LWsVEs9tp2vo2Ikd4gqX1ePFi_3Snm58Q

### Get list friend request to me
GET http://localhost:8080/api/friend-requests-to-me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1OTE5Nzc3LCJleHAiOjE1OTYwMDYxNzd9.hQ7xbFbjXdax07LRTfuQUMkola6Jt3QRuEessIc8lPxCdicB_OnA03BINSqB_V5--0hqjuzCIiEPGRXNixStdw


### Get list friend request from me
GET http://localhost:8080/api/friend-requests-from-me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1OTE5Nzc3LCJleHAiOjE1OTYwMDYxNzd9.hQ7xbFbjXdax07LRTfuQUMkola6Jt3QRuEessIc8lPxCdicB_OnA03BINSqB_V5--0hqjuzCIiEPGRXNixStdw
