PUT http://localhost:8080/api/comments/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0cm9uZ2RvYW4iLCJpYXQiOjE1OTU4OTk0NDUsImV4cCI6MTU5NTk4NTg0NX0.quFnjOmuqutJSlQY8tP0PlLjFu733vWM6eB5GBsasqckIpMQLYzWzfx_hAg33uMx4rQyOAtwK14vyp2NpQQnGw

{
  "content": "trong doan sua comment",
  "id": 16
}
###
DELETE http://localhost:8080/api/comments/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwaGkiLCJpYXQiOjE1OTYxMTcwOTUsImV4cCI6MTU5NjIwMzQ5NX0.yYYlgbq9P5WBkSEXDZH5h4eSisVhKLk7LWeeCQ86L63avuUB7e_NjeNM4XUUGRNKRKSNaDyMiPvPohrEnYNgKg

###
POST http://localhost:8080/api/posts/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoaWV1IiwiaWF0IjoxNTk1OTUwNTQwLCJleHAiOjE1OTYwMzY5NDB9.jdEvcDb6SuIJB2uQoNhV-ALwYp2RGUFi7TBEZP8VwxPjf7sJiUY5koI4OOutiLilQhvecdHu_PQJk_2knxCoZA


{
  "content": "toi  comment"
}
