GET http://localhost:8080/api/admin/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoaWV1IiwiaWF0IjoxNTk2MDgzNzA5LCJleHAiOjE1OTYxNzAxMDl9.v4INsONum0GIQe5sFfYnufOEgB0a2K4cDCXs-BX4Rx-qSo5lAw1Ca6SePA7wTAqE_jKukBg4bNL9J_mqQ0bY9g
###
POST http://localhost:8080/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1Nzg4MTczLCJleHAiOjE1OTU4NzQ1NzN9.z2mJ-wP_eqqlbpPrVimEQqwcrR6JsPeyKWnqUeWLhtZC_dI06htmzSp9GfwhIUsVv75NULMUbOTGzawbL0wuoA

{
  "status": 1,
  "content": "Thật là vl",
  "image": ""
}


### all post cua nguoi khac
GET http://localhost:8080/api/users/1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkdWMiLCJpYXQiOjE1OTY1MzExOTQsImV4cCI6MTU5NjYxNzU5NH0.J7Wsc7LNHUSENQUR_A01DIcUStioybPLxV_C2VMeUweObWlplYZ1mtMLlv9EvVuSmCe1eT4AcdLXo2PRJpxT-Q
