DELETE  http://localhost:8080/api/posts/1/reactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1Nzk5NjczLCJleHAiOjE1OTU4ODYwNzN9.YpEgogXdw2CFXqNLiGvpzgGx9MatJTxSskZVj0GC5zZN31P3kbW9A8iLIgdIe9O8s6DLIE9GqWfXNtp_JEkJqQ
