GET http://localhost:8080/api/posts/1/reactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1NzkzMDYyLCJleHAiOjE1OTU4Nzk0NjJ9.r1Y7hFVRwURxhXDHn1HBKoM_y0aaJlnXvtx26xjFUmmMzYzlbamf-TmazIVBlT_5389Q2KYLDtfVJ3nUxNTYHw
