GET http://localhost:8080/api/admin/users/statistics/today
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtMSIsImlhdCI6MTU5Njg4MjUwMywiZXhwIjoxNTk2OTY4OTAzfQ.c5qhk2A_T3QkuOSvdF2OgOZEIu0g1U6LRoA30hGdyAyYBK8b9vOZulgFPMr5iu6B5N4s4OYKvIsTOX7QLOvVTQ
Content-Type: application/json

###
POST http://localhost:8080/api/admin/users/statistics/range
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtMSIsImlhdCI6MTU5Njg3ODQ1MywiZXhwIjoxNTk2OTY0ODUzfQ.r4zC0D4_8UtmT4IyBw1O7d7-CKzf-GZGcd9upbDtY-6419yoSDV0lVicnuzBUSpGZfF4IbnM1Xc06OOUC7ZOFg
Content-Type: application/json

{
"start_date": "2020-05-31T17:00:00.000Z",
  "end_date": "2020-07-29T17:00:00.000Z"
}
