GET http://localhost:8080/api/admin/users/statistics/today
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtMSIsImlhdCI6MTU5Njg1NzMxNSwiZXhwIjoxNTk2OTQzNzE1fQ.ymHn_Eodq8kvcvyUHY9oKHd9JvsO9zAj8zyO51IYG30RWi2w51VE7_zE3u9qm07d-L5nZAm3tzdc-3nshYdHiQ
Content-Type: application/json

###
POST http://localhost:8080/api/admin/users/statistics/range
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk2ODU3MTc2LCJleHAiOjE1OTY5NDM1NzZ9.rb69pSrH24lo5fAiAuwgpPxMgnz0en5z5PC0hd4XAWdERx7ZBEYD7pMOmzYb93Bc_SbS57uRvaJCVnjueRV8qw
Content-Type: application/json

{
"start_date": "2020-05-31T17:00:00.000Z",
  "end_date": "2020-07-29T17:00:00.000Z"
}
