GET http://localhost:8080/api/users/date/20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1OTExNjIzLCJleHAiOjE1OTU5OTgwMjN9.y_UvU4gYuwFwlvgrl30RXyFx81Gifw-Ilxaghxze62oVyntoKM9Y23mpOZMtobDRL-USwN1J_KRyr-h2T58-yQ


###
GET http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1OTExNjIzLCJleHAiOjE1OTU5OTgwMjN9.y_UvU4gYuwFwlvgrl30RXyFx81Gifw-Ilxaghxze62oVyntoKM9Y23mpOZMtobDRL-USwN1J_KRyr-h2T58-yQ
