PUT http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1NzgzNzk3LCJleHAiOjE1OTU3ODM4ODR9.mUIsqO6P9H7B1O3_qDuqilij5V9OxDborQDRa79WPycsv2AdC2R97HJJKDhPsx6wDZT0NnrAShnxKnHDdB8Cdw

{
  "id": 2,
  "first_name": "van",
  "last_name": "duc",
  "email": "devteam@vndreamers.com",
  "birth_date": "1994-04-20",
  "username": "devteam",
  "address": "ha noi",
  "phone": "0987654321",
  "about_me": "luyen code nhu luyen co"
}

