PUT http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1NzgyNzE3LCJleHAiOjE1OTU3ODI4MDN9.XTtMO05xVVzDYrFfT6ak0CUUSZn5cD8Dom2PAXG6t_VnkSfvnYkqEpcvBoC0P6KGTdG1VDd9c9M6zujDZGulQQ

{
  "id": 1,
  "first_name": "van",
  "last_name": "duc",
  "email": "devteam@vndreamers.com",
  "birth_date": "1994-04-20",
  "username": "devteam",
  "address": "ha noi",
  "phone": "0987654321",
  "about_me": "luyen code nhu luyen co"
}

