PUT http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk1Nzg0MTU0LCJleHAiOjE1OTU4NzA1NTR9.xnjnjX5xQ5kDjARtBjK4Sdf-QC5--r3fT2ppk8J8SaRwIZj2S_NrZLrkUxHRfTpF1R9MQV-4-46LUo00FeOndw

{
  "id": 1,
  "first_name": "van",
  "last_name": "duc",
  "email": "devteam@vndreamers.com",
  "birth_date": "1994-04-20",
  "username": "devteam",
  "address": "ha noi",
  "phone": "0987654321",
  "about_me": "luyen code nhu luyen co"
}

