POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "dummy_email@example.com",
  "first_name": "dummy_first_name",
  "last_name" : "dummy_last_name",
  "password": "dummy_password",
  "confirm_password": "dummy_password",
  "birth_date": "20-04-2020",
  "status": 1
}

> {%
    client.test("Request thực hiện thành công", function() {
        client.assert(response.status === 200, "Status code trả về 200");
    });
%}

###
POST http://localhost:8080/auth/register
