POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "dummy_email@example.com",
  "password": "dummy_password",
  "confirm_password": "dummy_password",
  "phone": "0912345678",
  "birth_date": "20-04-2020",
  "status": 1,
  "avatar": "https://giaitri.vn/wp-content/uploads/2019/07/avatar-la-gi-01.jpg"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
